# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  name = "Home"
  pageRef = "/"
  weight = 5

[[main]]
  name = "Blog & News"
  identifier = "blog-news"
  pageRef="blog"
  weight=10

[[main]]
  name = "All Posts"
  parent = "blog-news"
  pageRef="blog"
  weight=10

[[main]]
  name = "Blog Posts"
  parent = "blog-news"
  pageRef="categories/blog"
  weight=11

[[main]]
  name = "Announcements"
  parent = "blog-news"
  pageRef="categories/announcements"
  weight=12

[[main]]
  name = "Details"
  identifier = "details"
  weight=15

[[main]]
  name = "Tracks"
  pageRef="tracks"
  parent = "details"
  weight=15

[[main]]
  name = "Prizes"
  pageRef="prizes"
  parent = "details"
  weight=20

[[main]]
  name = "Rules"
  pageRef="rules"
  parent = "details"
  weight=30

[[main]]
  name = "Timeline"
  pageRef="timeline"
  parent = "details"
  weight=35

[[main]]
  name = "Workshop Papers"
  pageRef="workshop-papers"
  parent = "details"
  weight=15

[[main]]
  name = "Participate"
  pageRef="participate"
  identifier = "participate-button"
  weight=50

[[main]]
  name = "FAQ"
  pageRef="faq"
  weight=40

[[main]]
  name = "Leaderboard"
  pageRef="leaderboard"
  weight=45

[[main]]
  name = "Speech Detection (Standard)"
  parent = "Leaderboard"
  pageRef = "speech_detection_standard"
  weight = 45

[[main]]
  name = "Speech Detection (Extended)"
  parent = "Leaderboard"
  pageRef = "speech_detection_extended"
  weight = 46

[[main]]
  name = "Phoneme Classification (Standard)"
  parent = "Leaderboard"
  pageRef = "phoneme_classification_standard"
  weight = 47

[[main]]
  name = "Phoneme Classification (Extended)"
  parent = "Leaderboard"
  pageRef = "phoneme_classification_extended"
  weight = 48

[[main]]
  name = "Organisers"
  pageRef="organisers"
  parent = "details"
  weight=40

[[main]]
  name = "Publications"
  pageRef="publications"
  parent = "details"
  weight=45
